services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:custom
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress:custom
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb:custom
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jalbiser/data/wordpress

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jalbiser/data/mysql

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
